const esModules = ["sonda.core.shared.components", "sonda.core.controls"].join("|");

module.exports = {
	rootDir: "src",
	testEnvironment: "jsdom",
	transform: {
		"^.+\\.(j|t)sx?$": "babel-jest",
		"^.+\\.svg$": "./../src/transform.svg.js",
		"^.+\\.jpg$": "./../src/transform.jpg.js",
	},
	preset: "ts-jest",
	setupFilesAfterEnv: ["../node_modules/@testing-library/jest-dom/dist/index.js"],
	transformIgnorePatterns: [`../../node_modules/(?!${esModules})`],
	moduleNameMapper: {
		"\\.(css)$": "identity-obj-proxy",
		"sonda.core.controls/importCSS": "sonda.core.controls/lib/importCSS.js",
		"sonda.core.controls/store": "sonda.core.controls/lib/store/index.js",
		"sonda.core.controls/commons": "sonda.core.controls/lib/components/commons/index.js",
		"sonda.core.controls/buttons": "sonda.core.controls/lib/components/commons/Buttons/index.js",
		"sonda.core.controls/checkbox": "sonda.core.controls/lib/components/commons/Checkboxs/index.js",
		"sonda.core.controls/combobox": "sonda.core.controls/lib/components/commons/ComboBox/index.js",
		"sonda.core.controls/datepicker":
			"sonda.core.controls/lib/components/commons/DatePicker/index.js",
		"sonda.core.controls/groupbuttons":
			"sonda.core.controls/lib/components/commons/GroupButtons/index.js",
		"sonda.core.controls/inputs": "sonda.core.controls/lib/components/commons/Inputs/index.js",
		"sonda.core.controls/listbox": "sonda.core.controls/lib/components/commons/ListBox/index.js",
		"sonda.core.controls/radio": "sonda.core.controls/lib/components/commons/RadioButtons/index.js",
		"sonda.core.controls/ranges": "sonda.core.controls/lib/components/commons/Ranges/index.js",
		"sonda.core.controls/switch": "sonda.core.controls/lib/components/commons/Switch/index.js",
		"sonda.core.controls/textarea": "sonda.core.controls/lib/components/commons/TextArea/index.js",
		"sonda.core.controls/upload": "sonda.core.controls/lib/components/commons/Upload/index.js",
		"sonda.core.controls/charts": "sonda.core.controls/lib/components/charts/index.js",
		"sonda.core.controls/dashboard": "sonda.core.controls/lib/components/dashboard/index.js",
		"sonda.core.controls/feedback": "sonda.core.controls/lib/components/feedback/index.js",
		"sonda.core.controls/icons": "sonda.core.controls/lib/components/icons/index.js",
		"sonda.core.controls/layout": "sonda.core.controls/lib/components/layout/index.js",
		"sonda.core.controls/localization": "sonda.core.controls/lib/components/localization/index.js",
		"sonda.core.controls/navigation": "sonda.core.controls/lib/components/navigation/index.js",
		"sonda.core.controls/privileges": "sonda.core.controls/lib/components/privileges/index.js",
		"sonda.core.controls/providers": "sonda.core.controls/lib/components/providers/index.js",
		"sonda.core.controls/specials": "sonda.core.controls/lib/components/specials/index.js",
		"sonda.core.controls/tables": "./lib/components/tables/index.js",
		"sonda.core.controls/time": "sonda.core.controls/lib/components/Time/index.js",
		"sonda.core.controls/typography": "sonda.core.controls/lib/components/typography/index.js",
	},
	collectCoverageFrom: ["**/*.{ts,tsx}", "!**/node_modules/**"],
	coverageDirectory: "__test__/coverage/",
	testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$",
	collectCoverage: true,
	modulePathIgnorePatterns: ["/cache", "/dist"],
	moduleDirectories: ["node_modules", "src"],
	moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
	coverageThreshold: {
		global: {
			branches: 20,
			functions: 20,
			lines: 20,
			statements: 20,
		},
	},
};
